//Ben Geary     RKB18204
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class DecisionTreeWhole extends Rides {



    BufferedReader input = new
            BufferedReader(new InputStreamReader(System.in));
    DecisionTree newTreeM;
    DecisionTree newTreeF;
    DecisionTree newTreeJ;
    DecisionTree newTreeI;



    public DecisionTreeWhole() throws IOException {
        newTreeM = new DecisionTree ();
        createTreeM();
        newTreeF = new DecisionTree();
        createTreeF();
        newTreeJ = new DecisionTree();
        createTreeJ();
        newTreeI = new DecisionTree();
        createTreeI();



    }


    void createTreeM() {
        System.out.println("Please Answer the following questions for Medieval Theme Rides");
        newTreeM.createRoot(1,"Do any of the people in your party use a wheelchair");
        newTreeM.addYes(1,2,"Is the smallest person if your group taller than 1? Answer Yes.");
        newTreeM.addNo(2,3,"Please restart program and answer yes to the question.");
        newTreeM.addYes(2,4,"Is the tallest Person in your group taller than 1m? Answer Yes.");
        newTreeM.addNo(4,5," Please Restart the program and answer Yes");
        newTreeM.addYes(4,6,"Is your group bigger than 1 and below 6?");
        newTreeM.addNo(6,7,"Do you like Addrenaline Rides?");
        newTreeM.addYes(6,8,"Do you Like Addrenaline rides?");
        newTreeM.addNo(7,9, "Do you like Horror rides?");
        newTreeM.addYes(7,10, "Do you like Horror rides?");
        newTreeM.addNo(8,11, "Do you like Horror rides?");
        newTreeM.addYes(8,12, "Do you like Horror rides?");
        newTreeM.addNo(9,13,"Do you like Kids Rides?");
        newTreeM.addYes(9,14,"Do you Like Kids rides?");
        newTreeM.addNo(10,15,"Do you like Kids Rides?");
        newTreeM.addYes(10,16,"Do you Like Kids rides?");
        newTreeM.addNo(11,17,"Do you like Kids Rides?");
        newTreeM.addYes(11,18,"Do you Like Kids rides?");
        newTreeM.addNo(12,19,"Do you like Kids Rides?");
        newTreeM.addYes(12,20,"Do you Like Kids rides?");
        newTreeM.addNo(13,21,"Do you like Water rides?");
        newTreeM.addYes(13,22,"Do you like Water rides?");
        newTreeM.addNo(14,23,"Do you like Water rides?");
        newTreeM.addYes(14,24,"Do you like Water rides?");
        newTreeM.addNo(15,25,"Do you like Water rides?");
        newTreeM.addYes(15,26,"Do you like Water rides?");
        newTreeM.addNo(16,27,"Do you like Water rides?");
        newTreeM.addYes(16,28,"Do you like Water rides?");
        newTreeM.addNo(17,29,"Do you like Water rides?");
        newTreeM.addYes(17,30,"Do you like Water rides?");
        newTreeM.addNo(18,31,"Do you like Water rides?");
        newTreeM.addYes(18,32,"Do you like Water rides?");
        newTreeM.addNo(19,33,"Do you like Water rides?");
        newTreeM.addYes(19,34,"Do you like Water rides?");
        newTreeM.addNo(20,35,"Do you like Water rides?");
        newTreeM.addYes(20,36,"Do you like Water rides?");
        newTreeM.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
        newTreeM.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
        newTreeM.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
        newTreeM.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
        newTreeM.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
        newTreeM.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
        newTreeM.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
        newTreeM.addYes(40,44,"Do you like Addrenaline Rides?");
        newTreeM.addNo(40,45, "Do you like Addrenaline Rides?");
        newTreeM.addYes(41,46,"Do you like Addrenaline Rides?");
        newTreeM.addNo(41,47,"Do you like Addrenaline Rides?");
        newTreeM.addYes(42,48,"Do you like Addrenaline Rides?");
        newTreeM.addNo(42,49, "Do you like Addrenaline Rides?");
        newTreeM.addYes(43,50,"Do you like Addrenaline Rides?");
        newTreeM.addNo(43,51,"Do you like Addrenaline Rides?");
        newTreeM.addYes(44,52,"Do you like Horror rides?");
        newTreeM.addNo(44,53,"Do you like Horror rides?");
        newTreeM.addYes(45,54,"Do you like Horror rides?");
        newTreeM.addNo(45,55,"Do you like Horror rides?");
        newTreeM.addYes(46,56,"Do you like Horror rides?");
        newTreeM.addNo(46,57,"Do you like Horror rides?");
        newTreeM.addYes(47,58,"Do you like Horror rides?");
        newTreeM.addNo(47,59,"Do you like Horror rides?");
        newTreeM.addYes(48,60,"Do you like Horror rides?");
        newTreeM.addNo(48,61,"Do you like Horror rides?");
        newTreeM.addYes(49,62,"Do you like Horror rides?");
        newTreeM.addNo(49,63,"Do you like Horror rides?");
        newTreeM.addYes(50,64,"Do you like Horror rides?");
        newTreeM.addNo(50,65,"Do you like Horror rides?");
        newTreeM.addYes(51,66,"Do you like Horror rides?");
        newTreeM.addNo(51,67,"Do you like Horror rides?");
        newTreeM.addNo(52,68,"Do you like Kids Rides?");
        newTreeM.addYes(52,69,"Do you Like Kids rides?");
        newTreeM.addNo(53,70,"Do you like Kids Rides?");
        newTreeM.addYes(53,71,"Do you Like Kids rides?");
        newTreeM.addNo(54,72,"Do you like Kids Rides?");
        newTreeM.addYes(54,73,"Do you Like Kids rides?");
        newTreeM.addNo(55,74,"Do you like Kids Rides?");
        newTreeM.addYes(55,75,"Do you Like Kids rides?");
        newTreeM.addNo(56,76,"Do you like Kids Rides?");
        newTreeM.addYes(56,77,"Do you Like Kids rides?");
        newTreeM.addNo(57,78,"Do you like Kids Rides?");
        newTreeM.addYes(57,79,"Do you Like Kids rides?");
        newTreeM.addNo(58,80,"Do you like Kids Rides?");
        newTreeM.addYes(58,81,"Do you Like Kids rides?");
        newTreeM.addNo(59,82,"Do you like Kids Rides?");
        newTreeM.addYes(59,83,"Do you Like Kids rides?");
        newTreeM.addNo(60,84,"Do you like Kids Rides?");
        newTreeM.addYes(60,85,"Do you Like Kids rides?");
        newTreeM.addNo(61,86,"Do you like Kids Rides?");
        newTreeM.addYes(61,87,"Do you Like Kids rides?");
        newTreeM.addNo(62,88,"Do you like Kids Rides?");
        newTreeM.addYes(62,89,"Do you Like Kids rides?");
        newTreeM.addNo(63,90,"Do you like Kids Rides?");
        newTreeM.addYes(63,91,"Do you Like Kids rides?");
        newTreeM.addNo(64,92,"Do you like Kids Rides?");
        newTreeM.addYes(64,93,"Do you Like Kids rides?");
        newTreeM.addNo(65,94,"Do you like Kids Rides?");
        newTreeM.addYes(65,95,"Do you Like Kids rides?");
        newTreeM.addNo(66,96,"Do you like Kids Rides?");
        newTreeM.addYes(66,97,"Do you Like Kids rides?");
        newTreeM.addNo(67,98,"Do you like Kids Rides?");
        newTreeM.addYes(67,99,"Do you Like Kids rides?");
        newTreeM.addNo(68,100,"Do you like Water rides?");
        newTreeM.addYes(68,101,"Do you like Water rides?");
        newTreeM.addNo(69,100,"Do you like Water rides?");
        newTreeM.addYes(69,101,"Do you like Water rides?");
        newTreeM.addNo(70,102,"Do you like Water rides?");
        newTreeM.addYes(70,103,"Do you like Water rides?");
        newTreeM.addNo(71,104,"Do you like Water rides?");
        newTreeM.addYes(71,105,"Do you like Water rides?");
        newTreeM.addNo(72,106,"Do you like Water rides?");
        newTreeM.addYes(72,107,"Do you like Water rides?");
        newTreeM.addNo(73,108,"Do you like Water rides?");
        newTreeM.addYes(73,109,"Do you like Water rides?");
        newTreeM.addNo(74,110,"Do you like Water rides?");
        newTreeM.addYes(74,111,"Do you like Water rides?");
        newTreeM.addNo(75,112,"Do you like Water rides?");
        newTreeM.addYes(75,113,"Do you like Water rides?");
        newTreeM.addNo(76,114,"Do you like Water rides?");
        newTreeM.addYes(76,115,"Do you like Water rides?");
        newTreeM.addNo(77,116,"Do you like Water rides?");
        newTreeM.addYes(77,117,"Do you like Water rides?");
        newTreeM.addNo(78,118,"Do you like Water rides?");
        newTreeM.addYes(78,119,"Do you like Water rides?");
        newTreeM.addNo(79,120,"Do you like Water rides?");
        newTreeM.addYes(79,121,"Do you like Water rides?");
        newTreeM.addNo(80,122,"Do you like Water rides?");
        newTreeM.addYes(80,123,"Do you like Water rides?");
        newTreeM.addNo(81,124,"Do you like Water rides?");
        newTreeM.addYes(81,125,"Do you like Water rides?");
        newTreeM.addNo(82,126,"Do you like Water rides?");
        newTreeM.addYes(82,127,"Do you like Water rides?");
        newTreeM.addNo(83,128,"Do you like Water rides?");
        newTreeM.addYes(83,129,"Do you like Water rides?");
        newTreeM.addNo(84,130,"Do you like Water rides?");
        newTreeM.addYes(84,131,"Do you like Water rides?");
        newTreeM.addNo(85,132,"Do you like Water rides?");
        newTreeM.addYes(85,133,"Do you like Water rides?");
        newTreeM.addNo(86,134,"Do you like Water rides?");
        newTreeM.addYes(86,135,"Do you like Water rides?");
        newTreeM.addNo(87,136,"Do you like Water rides?");
        newTreeM.addYes(87,137,"Do you like Water rides?");
        newTreeM.addNo(88,138,"Do you like Water rides?");
        newTreeM.addYes(88,139,"Do you like Water rides?");
        newTreeM.addNo(89,140,"Do you like Water rides?");
        newTreeM.addYes(89,141,"Do you like Water rides?");
        newTreeM.addNo(90,142,"Do you like Water rides?");
        newTreeM.addYes(90,143,"Do you like Water rides?");
        newTreeM.addNo(91,144,"Do you like Water rides?");
        newTreeM.addYes(91,145,"Do you like Water rides?");
        newTreeM.addNo(92,146,"Do you like Water rides?");
        newTreeM.addYes(92,147,"Do you like Water rides?");
        newTreeM.addNo(93,148,"Do you like Water rides?");
        newTreeM.addYes(93,149,"Do you like Water rides?");
        newTreeM.addNo(94,150,"Do you like Water rides?");
        newTreeM.addYes(94,151,"Do you like Water rides?");
        newTreeM.addNo(95,152,"Do you like Water rides?");
        newTreeM.addYes(95,153,"Do you like Water rides?");
        newTreeM.addNo(96,154,"Do you like Water rides?");
        newTreeM.addYes(96,155,"Do you like Water rides?");
        newTreeM.addNo(97,156,"Do you like Water rides?");
        newTreeM.addYes(97,157,"Do you like Water rides?");
        newTreeM.addNo(98,158,"Do you like Water rides?");
        newTreeM.addYes(98,159,"Do you like Water rides?");


        }

        void createTreeF(){
            System.out.println("Please Answer the following questions for Futuristic Theme Rides");
            newTreeF.createRoot(1,"Do any of the people in your party use a wheelchair");
            newTreeF.addYes(1,2,"Is the smallest person if your group less than 1.6m? Answer Yes.");
            newTreeF.addNo(2,3,"Please restart program and answer yes to the question.");
            newTreeF.addYes(2,4,"Is the tallest Person in your group taller than 1.6m? Answer Yes.");
            newTreeF.addNo(4,5," Please Restart the program and answer Yes");
            newTreeF.addYes(4,6,"Is your group bigger than 1 and below 8 or between 2 and 6 peopleit?");
            newTreeF.addNo(6,7,"Do you like Addrenaline Rides?");
            newTreeF.addYes(6,8,"Do you Like Addrenaline rides?");
            newTreeF.addNo(7,9, "Do you like Horror rides?");
            newTreeF.addYes(7,10, "Do you like Horror rides?");
            newTreeF.addNo(8,11, "Do you like Horror rides?");
            newTreeF.addYes(8,12, "Do you like Horror rides?");
            newTreeF.addNo(9,13,"Do you like Kids Rides?");
            newTreeF.addYes(9,14,"Do you Like Kids rides?");
            newTreeF.addNo(10,15,"Do you like Kids Rides?");
            newTreeF.addYes(10,16,"Do you Like Kids rides?");
            newTreeF.addNo(11,17,"Do you like Kids Rides?");
            newTreeF.addYes(11,18,"Do you Like Kids rides?");
            newTreeF.addNo(12,19,"Do you like Kids Rides?");
            newTreeF.addYes(12,20,"Do you Like Kids rides?");
            newTreeF.addNo(13,21,"Do you like Water rides?");
            newTreeF.addYes(13,22,"Do you like Water rides?");
            newTreeF.addNo(14,23,"Do you like Water rides?");
            newTreeF.addYes(14,24,"Do you like Water rides?");
            newTreeF.addNo(15,25,"Do you like Water rides?");
            newTreeF.addYes(15,26,"Do you like Water rides?");
            newTreeF.addNo(16,27,"Do you like Water rides?");
            newTreeF.addYes(16,28,"Do you like Water rides?");
            newTreeF.addNo(17,29,"Do you like Water rides?");
            newTreeF.addYes(17,30,"Do you like Water rides?");
            newTreeF.addNo(18,31,"Do you like Water rides?");
            newTreeF.addYes(18,32,"Do you like Water rides?");
            newTreeF.addNo(19,33,"Do you like Water rides?");
            newTreeF.addYes(19,34,"Do you like Water rides?");
            newTreeF.addNo(20,35,"Do you like Water rides?");
            newTreeF.addYes(20,36,"Do you like Water rides?");
            newTreeF.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
            newTreeF.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
            newTreeF.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
            newTreeF.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
            newTreeF.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
            newTreeF.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
            newTreeF.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
            newTreeF.addYes(40,44,"Do you like Addrenaline Rides?");
            newTreeF.addNo(40,45, "Do you like Addrenaline Rides?");
            newTreeF.addYes(41,46,"Do you like Addrenaline Rides?");
            newTreeF.addNo(41,47,"Do you like Addrenaline Rides?");
            newTreeF.addYes(42,48,"Do you like Addrenaline Rides?");
            newTreeF.addNo(42,49, "Do you like Addrenaline Rides?");
            newTreeF.addYes(43,50,"Do you like Addrenaline Rides?");
            newTreeF.addNo(43,51,"Do you like Addrenaline Rides?");
            newTreeF.addYes(44,52,"Do you like Horror rides?");
            newTreeF.addNo(44,53,"Do you like Horror rides?");
            newTreeF.addYes(45,54,"Do you like Horror rides?");
            newTreeF.addNo(45,55,"Do you like Horror rides?");
            newTreeF.addYes(46,56,"Do you like Horror rides?");
            newTreeF.addNo(46,57,"Do you like Horror rides?");
            newTreeF.addYes(47,58,"Do you like Horror rides?");
            newTreeF.addNo(47,59,"Do you like Horror rides?");
            newTreeF.addYes(48,60,"Do you like Horror rides?");
            newTreeF.addNo(48,61,"Do you like Horror rides?");
            newTreeF.addYes(49,62,"Do you like Horror rides?");
            newTreeF.addNo(49,63,"Do you like Horror rides?");
            newTreeF.addYes(50,64,"Do you like Horror rides?");
            newTreeF.addNo(50,65,"Do you like Horror rides?");
            newTreeF.addYes(51,66,"Do you like Horror rides?");
            newTreeF.addNo(51,67,"Do you like Horror rides?");
            newTreeF.addNo(52,68,"Do you like Kids Rides?");
            newTreeF.addYes(52,69,"Do you Like Kids rides?");
            newTreeF.addNo(53,70,"Do you like Kids Rides?");
            newTreeF.addYes(53,71,"Do you Like Kids rides?");
            newTreeF.addNo(54,72,"Do you like Kids Rides?");
            newTreeF.addYes(54,73,"Do you Like Kids rides?");
            newTreeF.addNo(55,74,"Do you like Kids Rides?");
            newTreeF.addYes(55,75,"Do you Like Kids rides?");
            newTreeF.addNo(56,76,"Do you like Kids Rides?");
            newTreeF.addYes(56,77,"Do you Like Kids rides?");
            newTreeF.addNo(57,78,"Do you like Kids Rides?");
            newTreeF.addYes(57,79,"Do you Like Kids rides?");
            newTreeF.addNo(58,80,"Do you like Kids Rides?");
            newTreeF.addYes(58,81,"Do you Like Kids rides?");
            newTreeF.addNo(59,82,"Do you like Kids Rides?");
            newTreeF.addYes(59,83,"Do you Like Kids rides?");
            newTreeF.addNo(60,84,"Do you like Kids Rides?");
            newTreeF.addYes(60,85,"Do you Like Kids rides?");
            newTreeF.addNo(61,86,"Do you like Kids Rides?");
            newTreeF.addYes(61,87,"Do you Like Kids rides?");
            newTreeF.addNo(62,88,"Do you like Kids Rides?");
            newTreeF.addYes(62,89,"Do you Like Kids rides?");
            newTreeF.addNo(63,90,"Do you like Kids Rides?");
            newTreeF.addYes(63,91,"Do you Like Kids rides?");
            newTreeF.addNo(64,92,"Do you like Kids Rides?");
            newTreeF.addYes(64,93,"Do you Like Kids rides?");
            newTreeF.addNo(65,94,"Do you like Kids Rides?");
            newTreeF.addYes(65,95,"Do you Like Kids rides?");
            newTreeF.addNo(66,96,"Do you like Kids Rides?");
            newTreeF.addYes(66,97,"Do you Like Kids rides?");
            newTreeF.addNo(67,98,"Do you like Kids Rides?");
            newTreeF.addYes(67,99,"Do you Like Kids rides?");
            newTreeF.addNo(68,100,"Do you like Water rides?");
            newTreeF.addYes(68,101,"Do you like Water rides?");
            newTreeF.addNo(69,100,"Do you like Water rides?");
            newTreeF.addYes(69,101,"Do you like Water rides?");
            newTreeF.addNo(70,102,"Do you like Water rides?");
            newTreeF.addYes(70,103,"Do you like Water rides?");
            newTreeF.addNo(71,104,"Do you like Water rides?");
            newTreeF.addYes(71,105,"Do you like Water rides?");
            newTreeF.addNo(72,106,"Do you like Water rides?");
            newTreeF.addYes(72,107,"Do you like Water rides?");
            newTreeF.addNo(73,108,"Do you like Water rides?");
            newTreeF.addYes(73,109,"Do you like Water rides?");
            newTreeF.addNo(74,110,"Do you like Water rides?");
            newTreeF.addYes(74,111,"Do you like Water rides?");
            newTreeF.addNo(75,112,"Do you like Water rides?");
            newTreeF.addYes(75,113,"Do you like Water rides?");
            newTreeF.addNo(76,114,"Do you like Water rides?");
            newTreeF.addYes(76,115,"Do you like Water rides?");
            newTreeF.addNo(77,116,"Do you like Water rides?");
            newTreeF.addYes(77,117,"Do you like Water rides?");
            newTreeF.addNo(78,118,"Do you like Water rides?");
            newTreeF.addYes(78,119,"Do you like Water rides?");
            newTreeF.addNo(79,120,"Do you like Water rides?");
            newTreeF.addYes(79,121,"Do you like Water rides?");
            newTreeF.addNo(80,122,"Do you like Water rides?");
            newTreeF.addYes(80,123,"Do you like Water rides?");
            newTreeF.addNo(81,124,"Do you like Water rides?");
            newTreeF.addYes(81,125,"Do you like Water rides?");
            newTreeF.addNo(82,126,"Do you like Water rides?");
            newTreeF.addYes(82,127,"Do you like Water rides?");
            newTreeF.addNo(83,128,"Do you like Water rides?");
            newTreeF.addYes(83,129,"Do you like Water rides?");
            newTreeF.addNo(84,130,"Do you like Water rides?");
            newTreeF.addYes(84,131,"Do you like Water rides?");
            newTreeF.addNo(85,132,"Do you like Water rides?");
            newTreeF.addYes(85,133,"Do you like Water rides?");
            newTreeF.addNo(86,134,"Do you like Water rides?");
            newTreeF.addYes(86,135,"Do you like Water rides?");
            newTreeF.addNo(87,136,"Do you like Water rides?");
            newTreeF.addYes(87,137,"Do you like Water rides?");
            newTreeF.addNo(88,138,"Do you like Water rides?");
            newTreeF.addYes(88,139,"Do you like Water rides?");
            newTreeF.addNo(89,140,"Do you like Water rides?");
            newTreeF.addYes(89,141,"Do you like Water rides?");
            newTreeF.addNo(90,142,"Do you like Water rides?");
            newTreeF.addYes(90,143,"Do you like Water rides?");
            newTreeF.addNo(91,144,"Do you like Water rides?");
            newTreeF.addYes(91,145,"Do you like Water rides?");
            newTreeF.addNo(92,146,"Do you like Water rides?");
            newTreeF.addYes(92,147,"Do you like Water rides?");
            newTreeF.addNo(93,148,"Do you like Water rides?");
            newTreeF.addYes(93,149,"Do you like Water rides?");
            newTreeF.addNo(94,150,"Do you like Water rides?");
            newTreeF.addYes(94,151,"Do you like Water rides?");
            newTreeF.addNo(95,152,"Do you like Water rides?");
            newTreeF.addYes(95,153,"Do you like Water rides?");
            newTreeF.addNo(96,154,"Do you like Water rides?");
            newTreeF.addYes(96,155,"Do you like Water rides?");
            newTreeF.addNo(97,156,"Do you like Water rides?");
            newTreeF.addYes(97,157,"Do you like Water rides?");
            newTreeF.addNo(98,158,"Do you like Water rides?");
            newTreeF.addYes(98,159,"Do you like Water rides?");



        }

        void createTreeJ(){
            System.out.println("Please Answer the following questions Jurassic Theme Rides");
            newTreeJ.createRoot(1,"Do any of the people in your party use a wheelchair");
            newTreeJ.addYes(1,2,"Is the smallest person if your group taller than 1? Answer Yes.");
            newTreeJ.addNo(2,3,"Please restart program and answer yes to the question.");
            newTreeJ.addYes(2,4,"Is the tallest Person in your group taller than 1m? Answer Yes.");
            newTreeJ.addNo(4,5," Please Restart the program and answer Yes");
            newTreeJ.addYes(4,6,"Is your group bigger than 1 and below 6?");
            newTreeJ.addNo(6,7,"Do you like Addrenaline Rides?");
            newTreeJ.addYes(6,8,"Do you Like Addrenaline rides?");
            newTreeJ.addNo(7,9, "Do you like Horror rides?");
            newTreeJ.addYes(7,10, "Do you like Horror rides?");
            newTreeJ.addNo(8,11, "Do you like Horror rides?");
            newTreeJ.addYes(8,12, "Do you like Horror rides?");
            newTreeJ.addNo(9,13,"Do you like Kids Rides?");
            newTreeJ.addYes(9,14,"Do you Like Kids rides?");
            newTreeJ.addNo(10,15,"Do you like Kids Rides?");
            newTreeJ.addYes(10,16,"Do you Like Kids rides?");
            newTreeJ.addNo(11,17,"Do you like Kids Rides?");
            newTreeJ.addYes(11,18,"Do you Like Kids rides?");
            newTreeJ.addNo(12,19,"Do you like Kids Rides?");
            newTreeJ.addYes(12,20,"Do you Like Kids rides?");
            newTreeJ.addNo(13,21,"Do you like Water rides?");
            newTreeJ.addYes(13,22,"Do you like Water rides?");
            newTreeJ.addNo(14,23,"Do you like Water rides?");
            newTreeJ.addYes(14,24,"Do you like Water rides?");
            newTreeJ.addNo(15,25,"Do you like Water rides?");
            newTreeJ.addYes(15,26,"Do you like Water rides?");
            newTreeJ.addNo(16,27,"Do you like Water rides?");
            newTreeJ.addYes(16,28,"Do you like Water rides?");
            newTreeJ.addNo(17,29,"Do you like Water rides?");
            newTreeJ.addYes(17,30,"Do you like Water rides?");
            newTreeJ.addNo(18,31,"Do you like Water rides?");
            newTreeJ.addYes(18,32,"Do you like Water rides?");
            newTreeJ.addNo(19,33,"Do you like Water rides?");
            newTreeJ.addYes(19,34,"Do you like Water rides?");
            newTreeJ.addNo(20,35,"Do you like Water rides?");
            newTreeJ.addYes(20,36,"Do you like Water rides?");
            newTreeJ.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
            newTreeJ.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
            newTreeJ.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
            newTreeJ.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
            newTreeJ.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
            newTreeJ.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
            newTreeJ.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
            newTreeJ.addYes(40,44,"Do you like Addrenaline Rides?");
            newTreeJ.addNo(40,45, "Do you like Addrenaline Rides?");
            newTreeJ.addYes(41,46,"Do you like Addrenaline Rides?");
            newTreeJ.addNo(41,47,"Do you like Addrenaline Rides?");
            newTreeJ.addYes(42,48,"Do you like Addrenaline Rides?");
            newTreeJ.addNo(42,49, "Do you like Addrenaline Rides?");
            newTreeJ.addYes(43,50,"Do you like Addrenaline Rides?");
            newTreeJ.addNo(43,51,"Do you like Addrenaline Rides?");
            newTreeJ.addYes(44,52,"Do you like Horror rides?");
            newTreeJ.addNo(44,53,"Do you like Horror rides?");
            newTreeJ.addYes(45,54,"Do you like Horror rides?");
            newTreeJ.addNo(45,55,"Do you like Horror rides?");
            newTreeJ.addYes(46,56,"Do you like Horror rides?");
            newTreeJ.addNo(46,57,"Do you like Horror rides?");
            newTreeJ.addYes(47,58,"Do you like Horror rides?");
            newTreeJ.addNo(47,59,"Do you like Horror rides?");
            newTreeJ.addYes(48,60,"Do you like Horror rides?");
            newTreeJ.addNo(48,61,"Do you like Horror rides?");
            newTreeJ.addYes(49,62,"Do you like Horror rides?");
            newTreeJ.addNo(49,63,"Do you like Horror rides?");
            newTreeJ.addYes(50,64,"Do you like Horror rides?");
            newTreeJ.addNo(50,65,"Do you like Horror rides?");
            newTreeJ.addYes(51,66,"Do you like Horror rides?");
            newTreeJ.addNo(51,67,"Do you like Horror rides?");
            newTreeJ.addNo(52,68,"Do you like Kids Rides?");
            newTreeJ.addYes(52,69,"Do you Like Kids rides?");
            newTreeJ.addNo(53,70,"Do you like Kids Rides?");
            newTreeJ.addYes(53,71,"Do you Like Kids rides?");
            newTreeJ.addNo(54,72,"Do you like Kids Rides?");
            newTreeJ.addYes(54,73,"Do you Like Kids rides?");
            newTreeJ.addNo(55,74,"Do you like Kids Rides?");
            newTreeJ.addYes(55,75,"Do you Like Kids rides?");
            newTreeJ.addNo(56,76,"Do you like Kids Rides?");
            newTreeJ.addYes(56,77,"Do you Like Kids rides?");
            newTreeJ.addNo(57,78,"Do you like Kids Rides?");
            newTreeJ.addYes(57,79,"Do you Like Kids rides?");
            newTreeJ.addNo(58,80,"Do you like Kids Rides?");
            newTreeJ.addYes(58,81,"Do you Like Kids rides?");
            newTreeJ.addNo(59,82,"Do you like Kids Rides?");
            newTreeJ.addYes(59,83,"Do you Like Kids rides?");
            newTreeJ.addNo(60,84,"Do you like Kids Rides?");
            newTreeJ.addYes(60,85,"Do you Like Kids rides?");
            newTreeJ.addNo(61,86,"Do you like Kids Rides?");
            newTreeJ.addYes(61,87,"Do you Like Kids rides?");
            newTreeJ.addNo(62,88,"Do you like Kids Rides?");
            newTreeJ.addYes(62,89,"Do you Like Kids rides?");
            newTreeJ.addNo(63,90,"Do you like Kids Rides?");
            newTreeJ.addYes(63,91,"Do you Like Kids rides?");
            newTreeJ.addNo(64,92,"Do you like Kids Rides?");
            newTreeJ.addYes(64,93,"Do you Like Kids rides?");
            newTreeJ.addNo(65,94,"Do you like Kids Rides?");
            newTreeJ.addYes(65,95,"Do you Like Kids rides?");
            newTreeJ.addNo(66,96,"Do you like Kids Rides?");
            newTreeJ.addYes(66,97,"Do you Like Kids rides?");
            newTreeJ.addNo(67,98,"Do you like Kids Rides?");
            newTreeJ.addYes(67,99,"Do you Like Kids rides?");
            newTreeJ.addNo(68,100,"Do you like Water rides?");
            newTreeJ.addYes(68,101,"Do you like Water rides?");
            newTreeJ.addNo(69,100,"Do you like Water rides?");
            newTreeJ.addYes(69,101,"Do you like Water rides?");
            newTreeJ.addNo(70,102,"Do you like Water rides?");
            newTreeJ.addYes(70,103,"Do you like Water rides?");
            newTreeJ.addNo(71,104,"Do you like Water rides?");
            newTreeJ.addYes(71,105,"Do you like Water rides?");
            newTreeJ.addNo(72,106,"Do you like Water rides?");
            newTreeJ.addYes(72,107,"Do you like Water rides?");
            newTreeJ.addNo(73,108,"Do you like Water rides?");
            newTreeJ.addYes(73,109,"Do you like Water rides?");
            newTreeJ.addNo(74,110,"Do you like Water rides?");
            newTreeJ.addYes(74,111,"Do you like Water rides?");
            newTreeJ.addNo(75,112,"Do you like Water rides?");
            newTreeJ.addYes(75,113,"Do you like Water rides?");
            newTreeJ.addNo(76,114,"Do you like Water rides?");
            newTreeJ.addYes(76,115,"Do you like Water rides?");
            newTreeJ.addNo(77,116,"Do you like Water rides?");
            newTreeJ.addYes(77,117,"Do you like Water rides?");
            newTreeJ.addNo(78,118,"Do you like Water rides?");
            newTreeJ.addYes(78,119,"Do you like Water rides?");
            newTreeJ.addNo(79,120,"Do you like Water rides?");
            newTreeJ.addYes(79,121,"Do you like Water rides?");
            newTreeJ.addNo(80,122,"Do you like Water rides?");
            newTreeJ.addYes(80,123,"Do you like Water rides?");
            newTreeJ.addNo(81,124,"Do you like Water rides?");
            newTreeJ.addYes(81,125,"Do you like Water rides?");
            newTreeJ.addNo(82,126,"Do you like Water rides?");
            newTreeJ.addYes(82,127,"Do you like Water rides?");
            newTreeJ.addNo(83,128,"Do you like Water rides?");
            newTreeJ.addYes(83,129,"Do you like Water rides?");
            newTreeJ.addNo(84,130,"Do you like Water rides?");
            newTreeJ.addYes(84,131,"Do you like Water rides?");
            newTreeJ.addNo(85,132,"Do you like Water rides?");
            newTreeJ.addYes(85,133,"Do you like Water rides?");
            newTreeJ.addNo(86,134,"Do you like Water rides?");
            newTreeJ.addYes(86,135,"Do you like Water rides?");
            newTreeJ.addNo(87,136,"Do you like Water rides?");
            newTreeJ.addYes(87,137,"Do you like Water rides?");
            newTreeJ.addNo(88,138,"Do you like Water rides?");
            newTreeJ.addYes(88,139,"Do you like Water rides?");
            newTreeJ.addNo(89,140,"Do you like Water rides?");
            newTreeJ.addYes(89,141,"Do you like Water rides?");
            newTreeJ.addNo(90,142,"Do you like Water rides?");
            newTreeJ.addYes(90,143,"Do you like Water rides?");
            newTreeJ.addNo(91,144,"Do you like Water rides?");
            newTreeJ.addYes(91,145,"Do you like Water rides?");
            newTreeJ.addNo(92,146,"Do you like Water rides?");
            newTreeJ.addYes(92,147,"Do you like Water rides?");
            newTreeJ.addNo(93,148,"Do you like Water rides?");
            newTreeJ.addYes(93,149,"Do you like Water rides?");
            newTreeJ.addNo(94,150,"Do you like Water rides?");
            newTreeJ.addYes(94,151,"Do you like Water rides?");
            newTreeJ.addNo(95,152,"Do you like Water rides?");
            newTreeJ.addYes(95,153,"Do you like Water rides?");
            newTreeJ.addNo(96,154,"Do you like Water rides?");
            newTreeJ.addYes(96,155,"Do you like Water rides?");
            newTreeJ.addNo(97,156,"Do you like Water rides?");
            newTreeJ.addYes(97,157,"Do you like Water rides?");
            newTreeJ.addNo(98,158,"Do you like Water rides?");
            newTreeJ.addYes(98,159,"Do you like Water rides?");


        }

        void createTreeI(){
            System.out.println("Please Answer the following questions for Industrial Themed Rides");
            newTreeI.createRoot(1,"Do any of the people in your party use a wheelchair");
            newTreeI.addYes(1,2,"Is the smallest person if your group taller than 1? Answer Yes.");
            newTreeI.addNo(2,3,"Please restart program and answer yes to the question.");
            newTreeI.addYes(2,4,"Is the tallest Person in your group taller than 1m? Answer Yes.");
            newTreeI.addNo(4,5," Please Restart the program and answer Yes");
            newTreeI.addYes(4,6,"Is your group bigger than 1 and below 6?");
            newTreeI.addNo(6,7,"Do you like Addrenaline Rides?");
            newTreeI.addYes(6,8,"Do you Like Addrenaline rides?");
            newTreeI.addNo(7,9, "Do you like Horror rides?");
            newTreeI.addYes(7,10, "Do you like Horror rides?");
            newTreeI.addNo(8,11, "Do you like Horror rides?");
            newTreeI.addYes(8,12, "Do you like Horror rides?");
            newTreeI.addNo(9,13,"Do you like Kids Rides?");
            newTreeI.addYes(9,14,"Do you Like Kids rides?");
            newTreeI.addNo(10,15,"Do you like Kids Rides?");
            newTreeI.addYes(10,16,"Do you Like Kids rides?");
            newTreeI.addNo(11,17,"Do you like Kids Rides?");
            newTreeI.addYes(11,18,"Do you Like Kids rides?");
            newTreeI.addNo(12,19,"Do you like Kids Rides?");
            newTreeI.addYes(12,20,"Do you Like Kids rides?");
            newTreeI.addNo(13,21,"Do you like Water rides?");
            newTreeI.addYes(13,22,"Do you like Water rides?");
            newTreeI.addNo(14,23,"Do you like Water rides?");
            newTreeI.addYes(14,24,"Do you like Water rides?");
            newTreeI.addNo(15,25,"Do you like Water rides?");
            newTreeI.addYes(15,26,"Do you like Water rides?");
            newTreeI.addNo(16,27,"Do you like Water rides?");
            newTreeI.addYes(16,28,"Do you like Water rides?");
            newTreeI.addNo(17,29,"Do you like Water rides?");
            newTreeI.addYes(17,30,"Do you like Water rides?");
            newTreeI.addNo(18,31,"Do you like Water rides?");
            newTreeI.addYes(18,32,"Do you like Water rides?");
            newTreeI.addNo(19,33,"Do you like Water rides?");
            newTreeI.addYes(19,34,"Do you like Water rides?");
            newTreeI.addNo(20,35,"Do you like Water rides?");
            newTreeI.addYes(20,36,"Do you like Water rides?");
            newTreeI.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
            newTreeI.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
            newTreeI.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
            newTreeI.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
            newTreeI.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
            newTreeI.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
            newTreeI.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
            newTreeI.addYes(40,44,"Do you like Addrenaline Rides?");
            newTreeI.addNo(40,45, "Do you like Addrenaline Rides?");
            newTreeI.addYes(41,46,"Do you like Addrenaline Rides?");
            newTreeI.addNo(41,47,"Do you like Addrenaline Rides?");
            newTreeI.addYes(42,48,"Do you like Addrenaline Rides?");
            newTreeI.addNo(42,49, "Do you like Addrenaline Rides?");
            newTreeI.addYes(43,50,"Do you like Addrenaline Rides?");
            newTreeI.addNo(43,51,"Do you like Addrenaline Rides?");
            newTreeI.addYes(44,52,"Do you like Horror rides?");
            newTreeI.addNo(44,53,"Do you like Horror rides?");
            newTreeI.addYes(45,54,"Do you like Horror rides?");
            newTreeI.addNo(45,55,"Do you like Horror rides?");
            newTreeI.addYes(46,56,"Do you like Horror rides?");
            newTreeI.addNo(46,57,"Do you like Horror rides?");
            newTreeI.addYes(47,58,"Do you like Horror rides?");
            newTreeI.addNo(47,59,"Do you like Horror rides?");
            newTreeI.addYes(48,60,"Do you like Horror rides?");
            newTreeI.addNo(48,61,"Do you like Horror rides?");
            newTreeI.addYes(49,62,"Do you like Horror rides?");
            newTreeI.addNo(49,63,"Do you like Horror rides?");
            newTreeI.addYes(50,64,"Do you like Horror rides?");
            newTreeI.addNo(50,65,"Do you like Horror rides?");
            newTreeI.addYes(51,66,"Do you like Horror rides?");
            newTreeI.addNo(51,67,"Do you like Horror rides?");
            newTreeI.addNo(52,68,"Do you like Kids Rides?");
            newTreeI.addYes(52,69,"Do you Like Kids rides?");
            newTreeI.addNo(53,70,"Do you like Kids Rides?");
            newTreeI.addYes(53,71,"Do you Like Kids rides?");
            newTreeI.addNo(54,72,"Do you like Kids Rides?");
            newTreeI.addYes(54,73,"Do you Like Kids rides?");
            newTreeI.addNo(55,74,"Do you like Kids Rides?");
            newTreeI.addYes(55,75,"Do you Like Kids rides?");
            newTreeI.addNo(56,76,"Do you like Kids Rides?");
            newTreeI.addYes(56,77,"Do you Like Kids rides?");
            newTreeI.addNo(57,78,"Do you like Kids Rides?");
            newTreeI.addYes(57,79,"Do you Like Kids rides?");
            newTreeI.addNo(58,80,"Do you like Kids Rides?");
            newTreeI.addYes(58,81,"Do you Like Kids rides?");
            newTreeI.addNo(59,82,"Do you like Kids Rides?");
            newTreeI.addYes(59,83,"Do you Like Kids rides?");
            newTreeI.addNo(60,84,"Do you like Kids Rides?");
            newTreeI.addYes(60,85,"Do you Like Kids rides?");
            newTreeI.addNo(61,86,"Do you like Kids Rides?");
            newTreeI.addYes(61,87,"Do you Like Kids rides?");
            newTreeI.addNo(62,88,"Do you like Kids Rides?");
            newTreeI.addYes(62,89,"Do you Like Kids rides?");
            newTreeI.addNo(63,90,"Do you like Kids Rides?");
            newTreeI.addYes(63,91,"Do you Like Kids rides?");
            newTreeI.addNo(64,92,"Do you like Kids Rides?");
            newTreeI.addYes(64,93,"Do you Like Kids rides?");
            newTreeI.addNo(65,94,"Do you like Kids Rides?");
            newTreeI.addYes(65,95,"Do you Like Kids rides?");
            newTreeI.addNo(66,96,"Do you like Kids Rides?");
            newTreeI.addYes(66,97,"Do you Like Kids rides?");
            newTreeI.addNo(67,98,"Do you like Kids Rides?");
            newTreeI.addYes(67,99,"Do you Like Kids rides?");
            newTreeI.addNo(68,100,"Do you like Water rides?");
            newTreeI.addYes(68,101,"Do you like Water rides?");
            newTreeI.addNo(69,100,"Do you like Water rides?");
            newTreeI.addYes(69,101,"Do you like Water rides?");
            newTreeI.addNo(70,102,"Do you like Water rides?");
            newTreeI.addYes(70,103,"Do you like Water rides?");
            newTreeI.addNo(71,104,"Do you like Water rides?");
            newTreeI.addYes(71,105,"Do you like Water rides?");
            newTreeI.addNo(72,106,"Do you like Water rides?");
            newTreeI.addYes(72,107,"Do you like Water rides?");
            newTreeI.addNo(73,108,"Do you like Water rides?");
            newTreeI.addYes(73,109,"Do you like Water rides?");
            newTreeI.addNo(74,110,"Do you like Water rides?");
            newTreeI.addYes(74,111,"Do you like Water rides?");
            newTreeI.addNo(75,112,"Do you like Water rides?");
            newTreeI.addYes(75,113,"Do you like Water rides?");
            newTreeI.addNo(76,114,"Do you like Water rides?");
            newTreeI.addYes(76,115,"Do you like Water rides?");
            newTreeI.addNo(77,116,"Do you like Water rides?");
            newTreeI.addYes(77,117,"Do you like Water rides?");
            newTreeI.addNo(78,118,"Do you like Water rides?");
            newTreeI.addYes(78,119,"Do you like Water rides?");
            newTreeI.addNo(79,120,"Do you like Water rides?");
            newTreeI.addYes(79,121,"Do you like Water rides?");
            newTreeI.addNo(80,122,"Do you like Water rides?");
            newTreeI.addYes(80,123,"Do you like Water rides?");
            newTreeI.addNo(81,124,"Do you like Water rides?");
            newTreeI.addYes(81,125,"Do you like Water rides?");
            newTreeI.addNo(82,126,"Do you like Water rides?");
            newTreeI.addYes(82,127,"Do you like Water rides?");
            newTreeI.addNo(83,128,"Do you like Water rides?");
            newTreeI.addYes(83,129,"Do you like Water rides?");
            newTreeI.addNo(84,130,"Do you like Water rides?");
            newTreeI.addYes(84,131,"Do you like Water rides?");
            newTreeI.addNo(85,132,"Do you like Water rides?");
            newTreeI.addYes(85,133,"Do you like Water rides?");
            newTreeI.addNo(86,134,"Do you like Water rides?");
            newTreeI.addYes(86,135,"Do you like Water rides?");
            newTreeI.addNo(87,136,"Do you like Water rides?");
            newTreeI.addYes(87,137,"Do you like Water rides?");
            newTreeI.addNo(88,138,"Do you like Water rides?");
            newTreeI.addYes(88,139,"Do you like Water rides?");
            newTreeI.addNo(89,140,"Do you like Water rides?");
            newTreeI.addYes(89,141,"Do you like Water rides?");
            newTreeI.addNo(90,142,"Do you like Water rides?");
            newTreeI.addYes(90,143,"Do you like Water rides?");
            newTreeI.addNo(91,144,"Do you like Water rides?");
            newTreeI.addYes(91,145,"Do you like Water rides?");
            newTreeI.addNo(92,146,"Do you like Water rides?");
            newTreeI.addYes(92,147,"Do you like Water rides?");
            newTreeI.addNo(93,148,"Do you like Water rides?");
            newTreeI.addYes(93,149,"Do you like Water rides?");
            newTreeI.addNo(94,150,"Do you like Water rides?");
            newTreeI.addYes(94,151,"Do you like Water rides?");
            newTreeI.addNo(95,152,"Do you like Water rides?");
            newTreeI.addYes(95,153,"Do you like Water rides?");
            newTreeI.addNo(96,154,"Do you like Water rides?");
            newTreeI.addYes(96,155,"Do you like Water rides?");
            newTreeI.addNo(97,156,"Do you like Water rides?");
            newTreeI.addYes(97,157,"Do you like Water rides?");
            newTreeI.addNo(98,158,"Do you like Water rides?");
            newTreeI.addYes(98,159,"Do you like Water rides?");




        }

    void queryTree() throws IOException {
        System.out.println("");
        System.out.println("Welcome to TimeTravellers. Lets see what rides you can ride... Answer the following questions.");
        System.out.println("");
        System.out.println("=======================================================================================================");
        newTreeM.queryTree();
        newTreeF.queryTree();
        newTreeJ.queryTree();
        newTreeI.queryTree();
        optionToExit();
    }


    void optionToExit() throws IOException {
        System.out.println("Exit? (enter \"Yes\" or \"No\")");
        String answer = input.readLine();
        if (answer.equals("Yes")) return;
        else {
            if (answer.equals("No")) queryTree();
            else {
                System.out.println("ERROR: Must answer \"Yes\" or \"No\"");
                optionToExit();
            }
        }
    }
}