//Ben Geary     RKB18204
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class DecisionTreeWhole extends Rides {



    BufferedReader input = new
            BufferedReader(new InputStreamReader(System.in));
    DecisionTree newTree;



    public DecisionTreeWhole() throws IOException {
        newTree = new DecisionTree ();
        createTreeM();
        new Rides.MedievalAttributes();
        createTreeF();
        new Rides.FutrusticAttributes();
        createTreeJ();
        new Rides.JurassicAttributes();
        createTreeI();



    }


    void createTreeM() {
        System.out.println("Please Answer the following questions for Medieval Theme Rides");
        newTree.createRoot(1,"Do any of the people in your party use a wheelchair");
        newTree.addYes(1,2,"Is the smallest person if your group taller than 1? Answer Yes.");
        newTree.addNo(2,3,"Please restart program and answer yes to the question.");
        newTree.addYes(2,4,"Is the tallest Person in your group taller than 1m? Answer Yes.");
        newTree.addNo(4,5," Please Restart the program and answer Yes");
        newTree.addYes(4,6,"Is your group bigger than 1 and below 6?");
        newTree.addNo(6,7,"Do you like Addrenaline Rides?");
        newTree.addYes(6,8,"Do you Like Addrenaline rides?");
        newTree.addNo(7,9, "Do you like Horror rides?");
        newTree.addYes(7,10, "Do you like Horror rides?");
        newTree.addNo(8,11, "Do you like Horror rides?");
        newTree.addYes(8,12, "Do you like Horror rides?");
        newTree.addNo(9,13,"Do you like Kids Rides?");
        newTree.addYes(9,14,"Do you Like Kids rides?");
        newTree.addNo(10,15,"Do you like Kids Rides?");
        newTree.addYes(10,16,"Do you Like Kids rides?");
        newTree.addNo(11,17,"Do you like Kids Rides?");
        newTree.addYes(11,18,"Do you Like Kids rides?");
        newTree.addNo(12,19,"Do you like Kids Rides?");
        newTree.addYes(12,20,"Do you Like Kids rides?");
        newTree.addNo(13,21,"Do you like Water rides?");
        newTree.addYes(13,22,"Do you like Water rides?");
        newTree.addNo(14,23,"Do you like Water rides?");
        newTree.addYes(14,24,"Do you like Water rides?");
        newTree.addNo(15,25,"Do you like Water rides?");
        newTree.addYes(15,26,"Do you like Water rides?");
        newTree.addNo(16,27,"Do you like Water rides?");
        newTree.addYes(16,28,"Do you like Water rides?");
        newTree.addNo(17,29,"Do you like Water rides?");
        newTree.addYes(17,30,"Do you like Water rides?");
        newTree.addNo(18,31,"Do you like Water rides?");
        newTree.addYes(18,32,"Do you like Water rides?");
        newTree.addNo(19,33,"Do you like Water rides?");
        newTree.addYes(19,34,"Do you like Water rides?");
        newTree.addNo(20,35,"Do you like Water rides?");
        newTree.addYes(20,36,"Do you like Water rides?");
        newTree.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
        newTree.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
        newTree.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
        newTree.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
        newTree.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
        newTree.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
        newTree.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
        newTree.addYes(40,44,"Do you like Addrenaline Rides?");
        newTree.addNo(40,45, "Do you like Addrenaline Rides?");
        newTree.addYes(41,46,"Do you like Addrenaline Rides?");
        newTree.addNo(41,47,"Do you like Addrenaline Rides?");
        newTree.addYes(42,48,"Do you like Addrenaline Rides?");
        newTree.addNo(42,49, "Do you like Addrenaline Rides?");
        newTree.addYes(43,50,"Do you like Addrenaline Rides?");
        newTree.addNo(43,51,"Do you like Addrenaline Rides?");
        newTree.addYes(44,52,"Do you like Horror rides?");
        newTree.addNo(44,53,"Do you like Horror rides?");
        newTree.addYes(45,54,"Do you like Horror rides?");
        newTree.addNo(45,55,"Do you like Horror rides?");
        newTree.addYes(46,56,"Do you like Horror rides?");
        newTree.addNo(46,57,"Do you like Horror rides?");
        newTree.addYes(47,58,"Do you like Horror rides?");
        newTree.addNo(47,59,"Do you like Horror rides?");
        newTree.addYes(48,60,"Do you like Horror rides?");
        newTree.addNo(48,61,"Do you like Horror rides?");
        newTree.addYes(49,62,"Do you like Horror rides?");
        newTree.addNo(49,63,"Do you like Horror rides?");
        newTree.addYes(50,64,"Do you like Horror rides?");
        newTree.addNo(50,65,"Do you like Horror rides?");
        newTree.addYes(51,66,"Do you like Horror rides?");
        newTree.addNo(51,67,"Do you like Horror rides?");
        newTree.addNo(52,68,"Do you like Kids Rides?");
        newTree.addYes(52,69,"Do you Like Kids rides?");
        newTree.addNo(53,70,"Do you like Kids Rides?");
        newTree.addYes(53,71,"Do you Like Kids rides?");
        newTree.addNo(54,72,"Do you like Kids Rides?");
        newTree.addYes(54,73,"Do you Like Kids rides?");
        newTree.addNo(55,74,"Do you like Kids Rides?");
        newTree.addYes(55,75,"Do you Like Kids rides?");
        newTree.addNo(56,76,"Do you like Kids Rides?");
        newTree.addYes(56,77,"Do you Like Kids rides?");
        newTree.addNo(57,78,"Do you like Kids Rides?");
        newTree.addYes(57,79,"Do you Like Kids rides?");
        newTree.addNo(58,80,"Do you like Kids Rides?");
        newTree.addYes(58,81,"Do you Like Kids rides?");
        newTree.addNo(59,82,"Do you like Kids Rides?");
        newTree.addYes(59,83,"Do you Like Kids rides?");
        newTree.addNo(60,84,"Do you like Kids Rides?");
        newTree.addYes(60,85,"Do you Like Kids rides?");
        newTree.addNo(61,86,"Do you like Kids Rides?");
        newTree.addYes(61,87,"Do you Like Kids rides?");
        newTree.addNo(62,88,"Do you like Kids Rides?");
        newTree.addYes(62,89,"Do you Like Kids rides?");
        newTree.addNo(63,90,"Do you like Kids Rides?");
        newTree.addYes(63,91,"Do you Like Kids rides?");
        newTree.addNo(64,92,"Do you like Kids Rides?");
        newTree.addYes(64,93,"Do you Like Kids rides?");
        newTree.addNo(65,94,"Do you like Kids Rides?");
        newTree.addYes(65,95,"Do you Like Kids rides?");
        newTree.addNo(66,96,"Do you like Kids Rides?");
        newTree.addYes(66,97,"Do you Like Kids rides?");
        newTree.addNo(67,98,"Do you like Kids Rides?");
        newTree.addYes(67,99,"Do you Like Kids rides?");
        newTree.addNo(68,100,"Do you like Water rides?");
        newTree.addYes(68,101,"Do you like Water rides?");
        newTree.addNo(69,100,"Do you like Water rides?");
        newTree.addYes(69,101,"Do you like Water rides?");
        newTree.addNo(70,102,"Do you like Water rides?");
        newTree.addYes(70,103,"Do you like Water rides?");
        newTree.addNo(71,104,"Do you like Water rides?");
        newTree.addYes(71,105,"Do you like Water rides?");
        newTree.addNo(72,106,"Do you like Water rides?");
        newTree.addYes(72,107,"Do you like Water rides?");
        newTree.addNo(73,108,"Do you like Water rides?");
        newTree.addYes(73,109,"Do you like Water rides?");
        newTree.addNo(74,110,"Do you like Water rides?");
        newTree.addYes(74,111,"Do you like Water rides?");
        newTree.addNo(75,112,"Do you like Water rides?");
        newTree.addYes(75,113,"Do you like Water rides?");
        newTree.addNo(76,114,"Do you like Water rides?");
        newTree.addYes(76,115,"Do you like Water rides?");
        newTree.addNo(77,116,"Do you like Water rides?");
        newTree.addYes(77,117,"Do you like Water rides?");
        newTree.addNo(78,118,"Do you like Water rides?");
        newTree.addYes(78,119,"Do you like Water rides?");
        newTree.addNo(79,120,"Do you like Water rides?");
        newTree.addYes(79,121,"Do you like Water rides?");
        newTree.addNo(80,122,"Do you like Water rides?");
        newTree.addYes(80,123,"Do you like Water rides?");
        newTree.addNo(81,124,"Do you like Water rides?");
        newTree.addYes(81,125,"Do you like Water rides?");
        newTree.addNo(82,126,"Do you like Water rides?");
        newTree.addYes(82,127,"Do you like Water rides?");
        newTree.addNo(83,128,"Do you like Water rides?");
        newTree.addYes(83,129,"Do you like Water rides?");
        newTree.addNo(84,130,"Do you like Water rides?");
        newTree.addYes(84,131,"Do you like Water rides?");
        newTree.addNo(85,132,"Do you like Water rides?");
        newTree.addYes(85,133,"Do you like Water rides?");
        newTree.addNo(86,134,"Do you like Water rides?");
        newTree.addYes(86,135,"Do you like Water rides?");
        newTree.addNo(87,136,"Do you like Water rides?");
        newTree.addYes(87,137,"Do you like Water rides?");
        newTree.addNo(88,138,"Do you like Water rides?");
        newTree.addYes(88,139,"Do you like Water rides?");
        newTree.addNo(89,140,"Do you like Water rides?");
        newTree.addYes(89,141,"Do you like Water rides?");
        newTree.addNo(90,142,"Do you like Water rides?");
        newTree.addYes(90,143,"Do you like Water rides?");
        newTree.addNo(91,144,"Do you like Water rides?");
        newTree.addYes(91,145,"Do you like Water rides?");
        newTree.addNo(92,146,"Do you like Water rides?");
        newTree.addYes(92,147,"Do you like Water rides?");
        newTree.addNo(93,148,"Do you like Water rides?");
        newTree.addYes(93,149,"Do you like Water rides?");
        newTree.addNo(94,150,"Do you like Water rides?");
        newTree.addYes(94,151,"Do you like Water rides?");
        newTree.addNo(95,152,"Do you like Water rides?");
        newTree.addYes(95,153,"Do you like Water rides?");
        newTree.addNo(96,154,"Do you like Water rides?");
        newTree.addYes(96,155,"Do you like Water rides?");
        newTree.addNo(97,156,"Do you like Water rides?");
        newTree.addYes(97,157,"Do you like Water rides?");
        newTree.addNo(98,158,"Do you like Water rides?");
        newTree.addYes(98,159,"Do you like Water rides?");


        }

        void createTreeF(){
            System.out.println("Please Answer the following questions for Futuristic Theme Rides");
            newTree.createRoot(1,"Do any of the people in your party use a wheelchair");
            newTree.addYes(1,2,"Is the smallest person if your group less than 1.6m? Answer Yes.");
            newTree.addNo(2,3,"Please restart program and answer yes to the question.");
            newTree.addYes(2,4,"Is the tallest Person in your group taller than 1.6m? Answer Yes.");
            newTree.addNo(4,5," Please Restart the program and answer Yes");
            newTree.addYes(4,6,"Is your group bigger than 1 and below 8 or between 2 and 6 peopleit?");
            newTree.addNo(6,7,"Do you like Addrenaline Rides?");
            newTree.addYes(6,8,"Do you Like Addrenaline rides?");
            newTree.addNo(7,9, "Do you like Horror rides?");
            newTree.addYes(7,10, "Do you like Horror rides?");
            newTree.addNo(8,11, "Do you like Horror rides?");
            newTree.addYes(8,12, "Do you like Horror rides?");
            newTree.addNo(9,13,"Do you like Kids Rides?");
            newTree.addYes(9,14,"Do you Like Kids rides?");
            newTree.addNo(10,15,"Do you like Kids Rides?");
            newTree.addYes(10,16,"Do you Like Kids rides?");
            newTree.addNo(11,17,"Do you like Kids Rides?");
            newTree.addYes(11,18,"Do you Like Kids rides?");
            newTree.addNo(12,19,"Do you like Kids Rides?");
            newTree.addYes(12,20,"Do you Like Kids rides?");
            newTree.addNo(13,21,"Do you like Water rides?");
            newTree.addYes(13,22,"Do you like Water rides?");
            newTree.addNo(14,23,"Do you like Water rides?");
            newTree.addYes(14,24,"Do you like Water rides?");
            newTree.addNo(15,25,"Do you like Water rides?");
            newTree.addYes(15,26,"Do you like Water rides?");
            newTree.addNo(16,27,"Do you like Water rides?");
            newTree.addYes(16,28,"Do you like Water rides?");
            newTree.addNo(17,29,"Do you like Water rides?");
            newTree.addYes(17,30,"Do you like Water rides?");
            newTree.addNo(18,31,"Do you like Water rides?");
            newTree.addYes(18,32,"Do you like Water rides?");
            newTree.addNo(19,33,"Do you like Water rides?");
            newTree.addYes(19,34,"Do you like Water rides?");
            newTree.addNo(20,35,"Do you like Water rides?");
            newTree.addYes(20,36,"Do you like Water rides?");
            newTree.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
            newTree.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
            newTree.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
            newTree.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
            newTree.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
            newTree.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
            newTree.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
            newTree.addYes(40,44,"Do you like Addrenaline Rides?");
            newTree.addNo(40,45, "Do you like Addrenaline Rides?");
            newTree.addYes(41,46,"Do you like Addrenaline Rides?");
            newTree.addNo(41,47,"Do you like Addrenaline Rides?");
            newTree.addYes(42,48,"Do you like Addrenaline Rides?");
            newTree.addNo(42,49, "Do you like Addrenaline Rides?");
            newTree.addYes(43,50,"Do you like Addrenaline Rides?");
            newTree.addNo(43,51,"Do you like Addrenaline Rides?");
            newTree.addYes(44,52,"Do you like Horror rides?");
            newTree.addNo(44,53,"Do you like Horror rides?");
            newTree.addYes(45,54,"Do you like Horror rides?");
            newTree.addNo(45,55,"Do you like Horror rides?");
            newTree.addYes(46,56,"Do you like Horror rides?");
            newTree.addNo(46,57,"Do you like Horror rides?");
            newTree.addYes(47,58,"Do you like Horror rides?");
            newTree.addNo(47,59,"Do you like Horror rides?");
            newTree.addYes(48,60,"Do you like Horror rides?");
            newTree.addNo(48,61,"Do you like Horror rides?");
            newTree.addYes(49,62,"Do you like Horror rides?");
            newTree.addNo(49,63,"Do you like Horror rides?");
            newTree.addYes(50,64,"Do you like Horror rides?");
            newTree.addNo(50,65,"Do you like Horror rides?");
            newTree.addYes(51,66,"Do you like Horror rides?");
            newTree.addNo(51,67,"Do you like Horror rides?");
            newTree.addNo(52,68,"Do you like Kids Rides?");
            newTree.addYes(52,69,"Do you Like Kids rides?");
            newTree.addNo(53,70,"Do you like Kids Rides?");
            newTree.addYes(53,71,"Do you Like Kids rides?");
            newTree.addNo(54,72,"Do you like Kids Rides?");
            newTree.addYes(54,73,"Do you Like Kids rides?");
            newTree.addNo(55,74,"Do you like Kids Rides?");
            newTree.addYes(55,75,"Do you Like Kids rides?");
            newTree.addNo(56,76,"Do you like Kids Rides?");
            newTree.addYes(56,77,"Do you Like Kids rides?");
            newTree.addNo(57,78,"Do you like Kids Rides?");
            newTree.addYes(57,79,"Do you Like Kids rides?");
            newTree.addNo(58,80,"Do you like Kids Rides?");
            newTree.addYes(58,81,"Do you Like Kids rides?");
            newTree.addNo(59,82,"Do you like Kids Rides?");
            newTree.addYes(59,83,"Do you Like Kids rides?");
            newTree.addNo(60,84,"Do you like Kids Rides?");
            newTree.addYes(60,85,"Do you Like Kids rides?");
            newTree.addNo(61,86,"Do you like Kids Rides?");
            newTree.addYes(61,87,"Do you Like Kids rides?");
            newTree.addNo(62,88,"Do you like Kids Rides?");
            newTree.addYes(62,89,"Do you Like Kids rides?");
            newTree.addNo(63,90,"Do you like Kids Rides?");
            newTree.addYes(63,91,"Do you Like Kids rides?");
            newTree.addNo(64,92,"Do you like Kids Rides?");
            newTree.addYes(64,93,"Do you Like Kids rides?");
            newTree.addNo(65,94,"Do you like Kids Rides?");
            newTree.addYes(65,95,"Do you Like Kids rides?");
            newTree.addNo(66,96,"Do you like Kids Rides?");
            newTree.addYes(66,97,"Do you Like Kids rides?");
            newTree.addNo(67,98,"Do you like Kids Rides?");
            newTree.addYes(67,99,"Do you Like Kids rides?");
            newTree.addNo(68,100,"Do you like Water rides?");
            newTree.addYes(68,101,"Do you like Water rides?");
            newTree.addNo(69,100,"Do you like Water rides?");
            newTree.addYes(69,101,"Do you like Water rides?");
            newTree.addNo(70,102,"Do you like Water rides?");
            newTree.addYes(70,103,"Do you like Water rides?");
            newTree.addNo(71,104,"Do you like Water rides?");
            newTree.addYes(71,105,"Do you like Water rides?");
            newTree.addNo(72,106,"Do you like Water rides?");
            newTree.addYes(72,107,"Do you like Water rides?");
            newTree.addNo(73,108,"Do you like Water rides?");
            newTree.addYes(73,109,"Do you like Water rides?");
            newTree.addNo(74,110,"Do you like Water rides?");
            newTree.addYes(74,111,"Do you like Water rides?");
            newTree.addNo(75,112,"Do you like Water rides?");
            newTree.addYes(75,113,"Do you like Water rides?");
            newTree.addNo(76,114,"Do you like Water rides?");
            newTree.addYes(76,115,"Do you like Water rides?");
            newTree.addNo(77,116,"Do you like Water rides?");
            newTree.addYes(77,117,"Do you like Water rides?");
            newTree.addNo(78,118,"Do you like Water rides?");
            newTree.addYes(78,119,"Do you like Water rides?");
            newTree.addNo(79,120,"Do you like Water rides?");
            newTree.addYes(79,121,"Do you like Water rides?");
            newTree.addNo(80,122,"Do you like Water rides?");
            newTree.addYes(80,123,"Do you like Water rides?");
            newTree.addNo(81,124,"Do you like Water rides?");
            newTree.addYes(81,125,"Do you like Water rides?");
            newTree.addNo(82,126,"Do you like Water rides?");
            newTree.addYes(82,127,"Do you like Water rides?");
            newTree.addNo(83,128,"Do you like Water rides?");
            newTree.addYes(83,129,"Do you like Water rides?");
            newTree.addNo(84,130,"Do you like Water rides?");
            newTree.addYes(84,131,"Do you like Water rides?");
            newTree.addNo(85,132,"Do you like Water rides?");
            newTree.addYes(85,133,"Do you like Water rides?");
            newTree.addNo(86,134,"Do you like Water rides?");
            newTree.addYes(86,135,"Do you like Water rides?");
            newTree.addNo(87,136,"Do you like Water rides?");
            newTree.addYes(87,137,"Do you like Water rides?");
            newTree.addNo(88,138,"Do you like Water rides?");
            newTree.addYes(88,139,"Do you like Water rides?");
            newTree.addNo(89,140,"Do you like Water rides?");
            newTree.addYes(89,141,"Do you like Water rides?");
            newTree.addNo(90,142,"Do you like Water rides?");
            newTree.addYes(90,143,"Do you like Water rides?");
            newTree.addNo(91,144,"Do you like Water rides?");
            newTree.addYes(91,145,"Do you like Water rides?");
            newTree.addNo(92,146,"Do you like Water rides?");
            newTree.addYes(92,147,"Do you like Water rides?");
            newTree.addNo(93,148,"Do you like Water rides?");
            newTree.addYes(93,149,"Do you like Water rides?");
            newTree.addNo(94,150,"Do you like Water rides?");
            newTree.addYes(94,151,"Do you like Water rides?");
            newTree.addNo(95,152,"Do you like Water rides?");
            newTree.addYes(95,153,"Do you like Water rides?");
            newTree.addNo(96,154,"Do you like Water rides?");
            newTree.addYes(96,155,"Do you like Water rides?");
            newTree.addNo(97,156,"Do you like Water rides?");
            newTree.addYes(97,157,"Do you like Water rides?");
            newTree.addNo(98,158,"Do you like Water rides?");
            newTree.addYes(98,159,"Do you like Water rides?");



        }

        void createTreeJ(){
            System.out.println("Please Answer the following questions Jurassic Theme Rides");
            newTree.createRoot(1,"Do any of the people in your party use a wheelchair");
            newTree.addYes(1,2,"Is the smallest person if your group taller than 1? Answer Yes.");
            newTree.addNo(2,3,"Please restart program and answer yes to the question.");
            newTree.addYes(2,4,"Is the tallest Person in your group taller than 1m? Answer Yes.");
            newTree.addNo(4,5," Please Restart the program and answer Yes");
            newTree.addYes(4,6,"Is your group bigger than 1 and below 6?");
            newTree.addNo(6,7,"Do you like Addrenaline Rides?");
            newTree.addYes(6,8,"Do you Like Addrenaline rides?");
            newTree.addNo(7,9, "Do you like Horror rides?");
            newTree.addYes(7,10, "Do you like Horror rides?");
            newTree.addNo(8,11, "Do you like Horror rides?");
            newTree.addYes(8,12, "Do you like Horror rides?");
            newTree.addNo(9,13,"Do you like Kids Rides?");
            newTree.addYes(9,14,"Do you Like Kids rides?");
            newTree.addNo(10,15,"Do you like Kids Rides?");
            newTree.addYes(10,16,"Do you Like Kids rides?");
            newTree.addNo(11,17,"Do you like Kids Rides?");
            newTree.addYes(11,18,"Do you Like Kids rides?");
            newTree.addNo(12,19,"Do you like Kids Rides?");
            newTree.addYes(12,20,"Do you Like Kids rides?");
            newTree.addNo(13,21,"Do you like Water rides?");
            newTree.addYes(13,22,"Do you like Water rides?");
            newTree.addNo(14,23,"Do you like Water rides?");
            newTree.addYes(14,24,"Do you like Water rides?");
            newTree.addNo(15,25,"Do you like Water rides?");
            newTree.addYes(15,26,"Do you like Water rides?");
            newTree.addNo(16,27,"Do you like Water rides?");
            newTree.addYes(16,28,"Do you like Water rides?");
            newTree.addNo(17,29,"Do you like Water rides?");
            newTree.addYes(17,30,"Do you like Water rides?");
            newTree.addNo(18,31,"Do you like Water rides?");
            newTree.addYes(18,32,"Do you like Water rides?");
            newTree.addNo(19,33,"Do you like Water rides?");
            newTree.addYes(19,34,"Do you like Water rides?");
            newTree.addNo(20,35,"Do you like Water rides?");
            newTree.addYes(20,36,"Do you like Water rides?");
            newTree.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
            newTree.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
            newTree.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
            newTree.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
            newTree.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
            newTree.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
            newTree.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
            newTree.addYes(40,44,"Do you like Addrenaline Rides?");
            newTree.addNo(40,45, "Do you like Addrenaline Rides?");
            newTree.addYes(41,46,"Do you like Addrenaline Rides?");
            newTree.addNo(41,47,"Do you like Addrenaline Rides?");
            newTree.addYes(42,48,"Do you like Addrenaline Rides?");
            newTree.addNo(42,49, "Do you like Addrenaline Rides?");
            newTree.addYes(43,50,"Do you like Addrenaline Rides?");
            newTree.addNo(43,51,"Do you like Addrenaline Rides?");
            newTree.addYes(44,52,"Do you like Horror rides?");
            newTree.addNo(44,53,"Do you like Horror rides?");
            newTree.addYes(45,54,"Do you like Horror rides?");
            newTree.addNo(45,55,"Do you like Horror rides?");
            newTree.addYes(46,56,"Do you like Horror rides?");
            newTree.addNo(46,57,"Do you like Horror rides?");
            newTree.addYes(47,58,"Do you like Horror rides?");
            newTree.addNo(47,59,"Do you like Horror rides?");
            newTree.addYes(48,60,"Do you like Horror rides?");
            newTree.addNo(48,61,"Do you like Horror rides?");
            newTree.addYes(49,62,"Do you like Horror rides?");
            newTree.addNo(49,63,"Do you like Horror rides?");
            newTree.addYes(50,64,"Do you like Horror rides?");
            newTree.addNo(50,65,"Do you like Horror rides?");
            newTree.addYes(51,66,"Do you like Horror rides?");
            newTree.addNo(51,67,"Do you like Horror rides?");
            newTree.addNo(52,68,"Do you like Kids Rides?");
            newTree.addYes(52,69,"Do you Like Kids rides?");
            newTree.addNo(53,70,"Do you like Kids Rides?");
            newTree.addYes(53,71,"Do you Like Kids rides?");
            newTree.addNo(54,72,"Do you like Kids Rides?");
            newTree.addYes(54,73,"Do you Like Kids rides?");
            newTree.addNo(55,74,"Do you like Kids Rides?");
            newTree.addYes(55,75,"Do you Like Kids rides?");
            newTree.addNo(56,76,"Do you like Kids Rides?");
            newTree.addYes(56,77,"Do you Like Kids rides?");
            newTree.addNo(57,78,"Do you like Kids Rides?");
            newTree.addYes(57,79,"Do you Like Kids rides?");
            newTree.addNo(58,80,"Do you like Kids Rides?");
            newTree.addYes(58,81,"Do you Like Kids rides?");
            newTree.addNo(59,82,"Do you like Kids Rides?");
            newTree.addYes(59,83,"Do you Like Kids rides?");
            newTree.addNo(60,84,"Do you like Kids Rides?");
            newTree.addYes(60,85,"Do you Like Kids rides?");
            newTree.addNo(61,86,"Do you like Kids Rides?");
            newTree.addYes(61,87,"Do you Like Kids rides?");
            newTree.addNo(62,88,"Do you like Kids Rides?");
            newTree.addYes(62,89,"Do you Like Kids rides?");
            newTree.addNo(63,90,"Do you like Kids Rides?");
            newTree.addYes(63,91,"Do you Like Kids rides?");
            newTree.addNo(64,92,"Do you like Kids Rides?");
            newTree.addYes(64,93,"Do you Like Kids rides?");
            newTree.addNo(65,94,"Do you like Kids Rides?");
            newTree.addYes(65,95,"Do you Like Kids rides?");
            newTree.addNo(66,96,"Do you like Kids Rides?");
            newTree.addYes(66,97,"Do you Like Kids rides?");
            newTree.addNo(67,98,"Do you like Kids Rides?");
            newTree.addYes(67,99,"Do you Like Kids rides?");
            newTree.addNo(68,100,"Do you like Water rides?");
            newTree.addYes(68,101,"Do you like Water rides?");
            newTree.addNo(69,100,"Do you like Water rides?");
            newTree.addYes(69,101,"Do you like Water rides?");
            newTree.addNo(70,102,"Do you like Water rides?");
            newTree.addYes(70,103,"Do you like Water rides?");
            newTree.addNo(71,104,"Do you like Water rides?");
            newTree.addYes(71,105,"Do you like Water rides?");
            newTree.addNo(72,106,"Do you like Water rides?");
            newTree.addYes(72,107,"Do you like Water rides?");
            newTree.addNo(73,108,"Do you like Water rides?");
            newTree.addYes(73,109,"Do you like Water rides?");
            newTree.addNo(74,110,"Do you like Water rides?");
            newTree.addYes(74,111,"Do you like Water rides?");
            newTree.addNo(75,112,"Do you like Water rides?");
            newTree.addYes(75,113,"Do you like Water rides?");
            newTree.addNo(76,114,"Do you like Water rides?");
            newTree.addYes(76,115,"Do you like Water rides?");
            newTree.addNo(77,116,"Do you like Water rides?");
            newTree.addYes(77,117,"Do you like Water rides?");
            newTree.addNo(78,118,"Do you like Water rides?");
            newTree.addYes(78,119,"Do you like Water rides?");
            newTree.addNo(79,120,"Do you like Water rides?");
            newTree.addYes(79,121,"Do you like Water rides?");
            newTree.addNo(80,122,"Do you like Water rides?");
            newTree.addYes(80,123,"Do you like Water rides?");
            newTree.addNo(81,124,"Do you like Water rides?");
            newTree.addYes(81,125,"Do you like Water rides?");
            newTree.addNo(82,126,"Do you like Water rides?");
            newTree.addYes(82,127,"Do you like Water rides?");
            newTree.addNo(83,128,"Do you like Water rides?");
            newTree.addYes(83,129,"Do you like Water rides?");
            newTree.addNo(84,130,"Do you like Water rides?");
            newTree.addYes(84,131,"Do you like Water rides?");
            newTree.addNo(85,132,"Do you like Water rides?");
            newTree.addYes(85,133,"Do you like Water rides?");
            newTree.addNo(86,134,"Do you like Water rides?");
            newTree.addYes(86,135,"Do you like Water rides?");
            newTree.addNo(87,136,"Do you like Water rides?");
            newTree.addYes(87,137,"Do you like Water rides?");
            newTree.addNo(88,138,"Do you like Water rides?");
            newTree.addYes(88,139,"Do you like Water rides?");
            newTree.addNo(89,140,"Do you like Water rides?");
            newTree.addYes(89,141,"Do you like Water rides?");
            newTree.addNo(90,142,"Do you like Water rides?");
            newTree.addYes(90,143,"Do you like Water rides?");
            newTree.addNo(91,144,"Do you like Water rides?");
            newTree.addYes(91,145,"Do you like Water rides?");
            newTree.addNo(92,146,"Do you like Water rides?");
            newTree.addYes(92,147,"Do you like Water rides?");
            newTree.addNo(93,148,"Do you like Water rides?");
            newTree.addYes(93,149,"Do you like Water rides?");
            newTree.addNo(94,150,"Do you like Water rides?");
            newTree.addYes(94,151,"Do you like Water rides?");
            newTree.addNo(95,152,"Do you like Water rides?");
            newTree.addYes(95,153,"Do you like Water rides?");
            newTree.addNo(96,154,"Do you like Water rides?");
            newTree.addYes(96,155,"Do you like Water rides?");
            newTree.addNo(97,156,"Do you like Water rides?");
            newTree.addYes(97,157,"Do you like Water rides?");
            newTree.addNo(98,158,"Do you like Water rides?");
            newTree.addYes(98,159,"Do you like Water rides?");


        }

        void createTreeI(){
            System.out.println("Please Answer the following questions for Industrial Themed Rides");
            newTree.createRoot(1,"Do any of the people in your party use a wheelchair");
            newTree.addYes(1,2,"Is the smallest person if your group taller than 1? Answer Yes.");
            newTree.addNo(2,3,"Please restart program and answer yes to the question.");
            newTree.addYes(2,4,"Is the tallest Person in your group taller than 1m? Answer Yes.");
            newTree.addNo(4,5," Please Restart the program and answer Yes");
            newTree.addYes(4,6,"Is your group bigger than 1 and below 6?");
            newTree.addNo(6,7,"Do you like Addrenaline Rides?");
            newTree.addYes(6,8,"Do you Like Addrenaline rides?");
            newTree.addNo(7,9, "Do you like Horror rides?");
            newTree.addYes(7,10, "Do you like Horror rides?");
            newTree.addNo(8,11, "Do you like Horror rides?");
            newTree.addYes(8,12, "Do you like Horror rides?");
            newTree.addNo(9,13,"Do you like Kids Rides?");
            newTree.addYes(9,14,"Do you Like Kids rides?");
            newTree.addNo(10,15,"Do you like Kids Rides?");
            newTree.addYes(10,16,"Do you Like Kids rides?");
            newTree.addNo(11,17,"Do you like Kids Rides?");
            newTree.addYes(11,18,"Do you Like Kids rides?");
            newTree.addNo(12,19,"Do you like Kids Rides?");
            newTree.addYes(12,20,"Do you Like Kids rides?");
            newTree.addNo(13,21,"Do you like Water rides?");
            newTree.addYes(13,22,"Do you like Water rides?");
            newTree.addNo(14,23,"Do you like Water rides?");
            newTree.addYes(14,24,"Do you like Water rides?");
            newTree.addNo(15,25,"Do you like Water rides?");
            newTree.addYes(15,26,"Do you like Water rides?");
            newTree.addNo(16,27,"Do you like Water rides?");
            newTree.addYes(16,28,"Do you like Water rides?");
            newTree.addNo(17,29,"Do you like Water rides?");
            newTree.addYes(17,30,"Do you like Water rides?");
            newTree.addNo(18,31,"Do you like Water rides?");
            newTree.addYes(18,32,"Do you like Water rides?");
            newTree.addNo(19,33,"Do you like Water rides?");
            newTree.addYes(19,34,"Do you like Water rides?");
            newTree.addNo(20,35,"Do you like Water rides?");
            newTree.addYes(20,36,"Do you like Water rides?");
            newTree.addNo(1,37,"Is the smallsest Person in your group between 0.8m and 1.2m?");
            newTree.addYes(37,38,"Is the Tallest person in the group taller than or equal to 1m?");
            newTree.addNo(37,39,"Is the Tallest person in the group taller than or equal to 1m?");
            newTree.addYes(38,40,"Is the group Size bigger than 1 and less than 6");
            newTree.addNo(38,41,"Is the group Size bigger than 1 and less than 6" );
            newTree.addYes(39,42, "Is the group Size bigger than 1 and less than 6");
            newTree.addNo(39,43,"Is the group Size bigger than 1 and less than 6");
            newTree.addYes(40,44,"Do you like Addrenaline Rides?");
            newTree.addNo(40,45, "Do you like Addrenaline Rides?");
            newTree.addYes(41,46,"Do you like Addrenaline Rides?");
            newTree.addNo(41,47,"Do you like Addrenaline Rides?");
            newTree.addYes(42,48,"Do you like Addrenaline Rides?");
            newTree.addNo(42,49, "Do you like Addrenaline Rides?");
            newTree.addYes(43,50,"Do you like Addrenaline Rides?");
            newTree.addNo(43,51,"Do you like Addrenaline Rides?");
            newTree.addYes(44,52,"Do you like Horror rides?");
            newTree.addNo(44,53,"Do you like Horror rides?");
            newTree.addYes(45,54,"Do you like Horror rides?");
            newTree.addNo(45,55,"Do you like Horror rides?");
            newTree.addYes(46,56,"Do you like Horror rides?");
            newTree.addNo(46,57,"Do you like Horror rides?");
            newTree.addYes(47,58,"Do you like Horror rides?");
            newTree.addNo(47,59,"Do you like Horror rides?");
            newTree.addYes(48,60,"Do you like Horror rides?");
            newTree.addNo(48,61,"Do you like Horror rides?");
            newTree.addYes(49,62,"Do you like Horror rides?");
            newTree.addNo(49,63,"Do you like Horror rides?");
            newTree.addYes(50,64,"Do you like Horror rides?");
            newTree.addNo(50,65,"Do you like Horror rides?");
            newTree.addYes(51,66,"Do you like Horror rides?");
            newTree.addNo(51,67,"Do you like Horror rides?");
            newTree.addNo(52,68,"Do you like Kids Rides?");
            newTree.addYes(52,69,"Do you Like Kids rides?");
            newTree.addNo(53,70,"Do you like Kids Rides?");
            newTree.addYes(53,71,"Do you Like Kids rides?");
            newTree.addNo(54,72,"Do you like Kids Rides?");
            newTree.addYes(54,73,"Do you Like Kids rides?");
            newTree.addNo(55,74,"Do you like Kids Rides?");
            newTree.addYes(55,75,"Do you Like Kids rides?");
            newTree.addNo(56,76,"Do you like Kids Rides?");
            newTree.addYes(56,77,"Do you Like Kids rides?");
            newTree.addNo(57,78,"Do you like Kids Rides?");
            newTree.addYes(57,79,"Do you Like Kids rides?");
            newTree.addNo(58,80,"Do you like Kids Rides?");
            newTree.addYes(58,81,"Do you Like Kids rides?");
            newTree.addNo(59,82,"Do you like Kids Rides?");
            newTree.addYes(59,83,"Do you Like Kids rides?");
            newTree.addNo(60,84,"Do you like Kids Rides?");
            newTree.addYes(60,85,"Do you Like Kids rides?");
            newTree.addNo(61,86,"Do you like Kids Rides?");
            newTree.addYes(61,87,"Do you Like Kids rides?");
            newTree.addNo(62,88,"Do you like Kids Rides?");
            newTree.addYes(62,89,"Do you Like Kids rides?");
            newTree.addNo(63,90,"Do you like Kids Rides?");
            newTree.addYes(63,91,"Do you Like Kids rides?");
            newTree.addNo(64,92,"Do you like Kids Rides?");
            newTree.addYes(64,93,"Do you Like Kids rides?");
            newTree.addNo(65,94,"Do you like Kids Rides?");
            newTree.addYes(65,95,"Do you Like Kids rides?");
            newTree.addNo(66,96,"Do you like Kids Rides?");
            newTree.addYes(66,97,"Do you Like Kids rides?");
            newTree.addNo(67,98,"Do you like Kids Rides?");
            newTree.addYes(67,99,"Do you Like Kids rides?");
            newTree.addNo(68,100,"Do you like Water rides?");
            newTree.addYes(68,101,"Do you like Water rides?");
            newTree.addNo(69,100,"Do you like Water rides?");
            newTree.addYes(69,101,"Do you like Water rides?");
            newTree.addNo(70,102,"Do you like Water rides?");
            newTree.addYes(70,103,"Do you like Water rides?");
            newTree.addNo(71,104,"Do you like Water rides?");
            newTree.addYes(71,105,"Do you like Water rides?");
            newTree.addNo(72,106,"Do you like Water rides?");
            newTree.addYes(72,107,"Do you like Water rides?");
            newTree.addNo(73,108,"Do you like Water rides?");
            newTree.addYes(73,109,"Do you like Water rides?");
            newTree.addNo(74,110,"Do you like Water rides?");
            newTree.addYes(74,111,"Do you like Water rides?");
            newTree.addNo(75,112,"Do you like Water rides?");
            newTree.addYes(75,113,"Do you like Water rides?");
            newTree.addNo(76,114,"Do you like Water rides?");
            newTree.addYes(76,115,"Do you like Water rides?");
            newTree.addNo(77,116,"Do you like Water rides?");
            newTree.addYes(77,117,"Do you like Water rides?");
            newTree.addNo(78,118,"Do you like Water rides?");
            newTree.addYes(78,119,"Do you like Water rides?");
            newTree.addNo(79,120,"Do you like Water rides?");
            newTree.addYes(79,121,"Do you like Water rides?");
            newTree.addNo(80,122,"Do you like Water rides?");
            newTree.addYes(80,123,"Do you like Water rides?");
            newTree.addNo(81,124,"Do you like Water rides?");
            newTree.addYes(81,125,"Do you like Water rides?");
            newTree.addNo(82,126,"Do you like Water rides?");
            newTree.addYes(82,127,"Do you like Water rides?");
            newTree.addNo(83,128,"Do you like Water rides?");
            newTree.addYes(83,129,"Do you like Water rides?");
            newTree.addNo(84,130,"Do you like Water rides?");
            newTree.addYes(84,131,"Do you like Water rides?");
            newTree.addNo(85,132,"Do you like Water rides?");
            newTree.addYes(85,133,"Do you like Water rides?");
            newTree.addNo(86,134,"Do you like Water rides?");
            newTree.addYes(86,135,"Do you like Water rides?");
            newTree.addNo(87,136,"Do you like Water rides?");
            newTree.addYes(87,137,"Do you like Water rides?");
            newTree.addNo(88,138,"Do you like Water rides?");
            newTree.addYes(88,139,"Do you like Water rides?");
            newTree.addNo(89,140,"Do you like Water rides?");
            newTree.addYes(89,141,"Do you like Water rides?");
            newTree.addNo(90,142,"Do you like Water rides?");
            newTree.addYes(90,143,"Do you like Water rides?");
            newTree.addNo(91,144,"Do you like Water rides?");
            newTree.addYes(91,145,"Do you like Water rides?");
            newTree.addNo(92,146,"Do you like Water rides?");
            newTree.addYes(92,147,"Do you like Water rides?");
            newTree.addNo(93,148,"Do you like Water rides?");
            newTree.addYes(93,149,"Do you like Water rides?");
            newTree.addNo(94,150,"Do you like Water rides?");
            newTree.addYes(94,151,"Do you like Water rides?");
            newTree.addNo(95,152,"Do you like Water rides?");
            newTree.addYes(95,153,"Do you like Water rides?");
            newTree.addNo(96,154,"Do you like Water rides?");
            newTree.addYes(96,155,"Do you like Water rides?");
            newTree.addNo(97,156,"Do you like Water rides?");
            newTree.addYes(97,157,"Do you like Water rides?");
            newTree.addNo(98,158,"Do you like Water rides?");
            newTree.addYes(98,159,"Do you like Water rides?");




        }

    void queryTree() throws IOException {
        System.out.println("");
        System.out.println("Welcome to TimeTravellers. Lets see what rides you can ride... Answer the following questions.");
        System.out.println("");
        System.out.println("=======================================================================================================");
        newTree.queryTree();
        optionToExit();
    }


    void optionToExit() throws IOException {
        System.out.println("Exit? (enter \"Yes\" or \"No\")");
        String answer = input.readLine();
        if (answer.equals("Yes")) return;
        else {
            if (answer.equals("No")) queryTree();
            else {
                System.out.println("ERROR: Must answer \"Yes\" or \"No\"");
                optionToExit();
            }
        }
    }
}